#spring:
#  datasource:
#    username: mommauser
#    password: password
#    url: jdbc:mysql://localhost:3306/momma_db
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: true
#    properties.hibernate.dialect: org.hibernate.dialect.MySQLDialect